
import { Inter } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "@/components/context/login_context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
  <html lang="en">
    <body>
    
     
      <LoginProvider>

      <main>{children}</main>
        
      <div id="modal-root">  </div>
     
      </LoginProvider>
    </body>
  </html>
  )
    
}
