import { Inter } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "@/components/context/login_context";
import { CartProvider } from "@/components/context/cart_context";
import { LoginModalProvider } from "@/components/context/login_modal_context";
import NavbarWrapper from "@/components/NavbarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
  <html lang="en">
    <body>
    
      <LoginProvider>
      <CartProvider>
      <LoginModalProvider>

      <NavbarWrapper />
      <main>{children}</main>
        
      <div id="modal-root">  </div>
      
      </LoginModalProvider>
      </CartProvider>
      </LoginProvider>
    </body>
  </html>
  )
    
}